import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'
import { db } from '@/lib/firebase'
import { collection, addDoc, serverTimestamp } from 'firebase/firestore'

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY })

const DETECTOR_PROMPT_ID = 'pmpt_69a3e4f87a80819085db0e4788a6fccc08d5c2d98eb0c9da'
const DETECTOR_PROMPT_VERSION = '5'

export async function POST(req: NextRequest) {
    try {
        const body = await req.json()
        const {
            essay_content,
            // Optional metadata from client for logging
            studentId,
            studentName,
            essayTitle,
            topicName,
        } = body

        if (!essay_content?.trim()) {
            return NextResponse.json({ error: 'Essay content is required.' }, { status: 400 })
        }

        const response = await (openai as any).responses.create({
            prompt: {
                id: DETECTOR_PROMPT_ID,
                version: DETECTOR_PROMPT_VERSION,
                variables: { essay_content },
            },
        })

        const raw: string =
            response.output_text ??
            response.choices?.[0]?.message?.content ??
            ''

        // Determine verdict: if the response mentions "AI content" → reject
        const isAi = /ai[\s-]?content/i.test(raw) || /generated by ai/i.test(raw)
        const verdict = isAi ? 'ai' : 'human'

        // Log AI detections to Firestore (only when AI content is suspected)
        if (isAi && studentId) {
            try {
                await addDoc(collection(db, 'ai_detection_logs'), {
                    studentId,
                    studentName: studentName || 'Unknown',
                    essayTitle: essayTitle || 'Untitled',
                    topicName: topicName || 'Unknown Topic',
                    verdict,
                    detectedAt: serverTimestamp(),
                    // Store a short excerpt (first 200 chars) for context
                    excerpt: essay_content.trim().slice(0, 200),
                })
            } catch (logErr) {
                // Non-critical: don't fail the request if logging fails
                console.error('Failed to save AI detection log:', logErr)
            }
        }

        return NextResponse.json({ verdict, raw })
    } catch (err: any) {
        console.error('AI Detector error:', err)
        return NextResponse.json(
            { error: err?.message || 'AI detection failed. Please try again.' },
            { status: 500 }
        )
    }
}
