import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY })

const DETECTOR_PROMPT_ID = 'pmpt_69a3e4f87a80819085db0e4788a6fccc08d5c2d98eb0c9da'
const DETECTOR_PROMPT_VERSION = '5'

export async function POST(req: NextRequest) {
    try {
        const { essay_content } = await req.json()

        if (!essay_content?.trim()) {
            return NextResponse.json({ error: 'Essay content is required.' }, { status: 400 })
        }

        const response = await (openai as any).responses.create({
            prompt: {
                id: DETECTOR_PROMPT_ID,
                version: DETECTOR_PROMPT_VERSION,
                variables: { essay_content },
            },
        })

        const raw: string =
            response.output_text ??
            response.choices?.[0]?.message?.content ??
            ''

        // Determine verdict: if the response mentions "AI content" → reject
        const isAi = /ai[\s-]?content/i.test(raw) || /generated by ai/i.test(raw)

        return NextResponse.json({
            verdict: isAi ? 'ai' : 'human',
            raw,
        })
    } catch (err: any) {
        console.error('AI Detector error:', err)
        return NextResponse.json(
            { error: err?.message || 'AI detection failed. Please try again.' },
            { status: 500 }
        )
    }
}
